"""new table structure

Revision ID: 170833716db6
Revises: d66bb6f56349
Create Date: 2023-01-16 14:16:17.937868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '170833716db6'
down_revision = 'd66bb6f56349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifikasi',
    sa.Column('id_verifikasi', sa.BigInteger(), nullable=False),
    sa.Column('waktu_verifikasi', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.String(length=100), nullable=False),
    sa.Column('tps', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id_verifikasi')
    )
    op.drop_table('foto_pemilih')
    with op.batch_alter_table('pemilih', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('foto_ktp', sa.String(length=100), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('no_telepon')
        batch_op.drop_column('nama_pemilih')
        batch_op.drop_column('alamat')

    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_tps', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('alamat', sa.String(length=230), nullable=False))
        batch_op.drop_column('alamat_tps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alamat_tps', mysql.VARCHAR(length=230), nullable=False))
        batch_op.drop_column('alamat')
        batch_op.drop_column('no_tps')

    with op.batch_alter_table('pemilih', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alamat', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('nama_pemilih', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('no_telepon', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('foto_ktp')
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('nama')

    op.create_table('foto_pemilih',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('namafoto', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_pemilih', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_pemilih'], ['pemilih.id'], name='foto_pemilih_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('verifikasi')
    # ### end Alembic commands ###
