"""users table only

Revision ID: d66bb6f56349
Revises: 
Create Date: 2022-12-22 14:06:30.150724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66bb6f56349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alamat_tps', sa.String(length=230), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pemilih',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nama_pemilih', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('no_telepon', sa.String(length=15), nullable=False),
    sa.Column('tps', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tps'], ['tps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto_pemilih',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('namafoto', sa.String(length=100), nullable=False),
    sa.Column('id_pemilih', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_pemilih'], ['pemilih.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foto_pemilih')
    op.drop_table('pemilih')
    op.drop_table('tps')
    # ### end Alembic commands ###
